<?php

/* $Id: en.lang.php 6207 2012-02-10 10:14:50Z denis $ */

define("NETCAT_MODULE_FILEMANAGER_DESCRIPTION", "The module allows you to manage files on the server");

// admin
define("NETCAT_MODULE_FILEMANAGER_ADMIN_CURRENT", "current");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR", "dir");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_SIZE", "size");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PERMISSION", "permission");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ACTION", "action");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_TOTAL", "total");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_UPLOAD_FILE", "upload file");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_CREATE_DIR", "create new dir");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DELETE", "delete");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_EDIT", "edit");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DOWNLOAD", "download");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_SETTINGS", "settings");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ROOT_LINK", "begining");

// buttons
define("NETCAT_MODULE_FILEMANAGER_ADMIN_SAVE_BUTTON", "Save");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_REWRITE_BUTTON", "Rewrite");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_REFRESH_BUTTON", "Refresh");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DELETE_BUTTON", "Delete");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_CANCEL_BUTTON", "Cancel");

// dialogs
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_DIR_DELETE", "Delete dir %s?");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_FILE_DELETE", "Delete file %s?");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIALOG_FILE_REWRITE", "Rewrite file %s?");

// succesfully
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_UPDATED", "File %s succesfully updated");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_UPLOADED", "File %s succesfully uploaded");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_REWRITED", "File %s succesfully rewrited");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_DELETED", "File %s succesfully deleted");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_CREATED", "Dir %s succesfully created");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_DELETED", "Dir %s succesfully deleted");

// other
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V1", "dir");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V2", "dirs");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_DIR_V3", "dirs");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V1", "file");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V2", "files");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_FILE_V3", "files");

// panel
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_OWNER", "Owner permissions");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_GROUP", "Group permissions");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_PUBLIC", "Public permissions");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_READ", "read");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_WRITE", "write");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_EXECUTE", "executable");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_RENAME", "Rename");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_CLOSE", "Close");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_PANEL_SAVE", "Save");

// errors
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_NOT_EXIST", "Dir %s does not exist");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_ALREADY_EXIST", "Dir %s already exist");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_WRITE_PERMISSION", "Insufficient rights to write to the directory %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_DELETE_PERMISSION", "Insufficient rights to delete a directory %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_READ_PERMISSION", "Insufficient rights to read the directory %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_DIR_CREATE", "Dir %s write error");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_NOT_EXIST", "File %s does not exist");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_WRITE_PERMISSION", "Insufficient rights to write to the file %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_DELETE_PERMISSION", "Insufficient rights to delete a file %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_READ_PERMISSION", "Insufficient rights to read a file %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_WRITE", "File %s write error");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_FILE_UPLOAD", "File %s upload error");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_NOT_EXIST", "Object %s does not exist");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_CHMOD", "Сan not change the rights to the object %s");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_UNDEFINED_ACTION", "This action not available");
define("NETCAT_MODULE_FILEMANAGER_ADMIN_ERROR_PATH", "Invalid value %s");
?>